// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/srv/SetSimState.srv - do not modify

#include "Srvs/ROS2SetSimState.h"





const rosidl_service_type_support_t* UROS2SetSimStateSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(rosflight_msgs, srv, SetSimState);
}

void UROS2SetSimStateSrv::Init()
{
    rosflight_msgs__srv__SetSimState_Request__init(&SetSimState_req);
    rosflight_msgs__srv__SetSimState_Response__init(&SetSimState_res);
}

void UROS2SetSimStateSrv::Fini()
{
    rosflight_msgs__srv__SetSimState_Request__fini(&SetSimState_req);
    rosflight_msgs__srv__SetSimState_Response__fini(&SetSimState_res);
}

void UROS2SetSimStateSrv::SetRequest(const FROSSetSimStateReq& Request)
{
    Request.SetROS2(SetSimState_req);
}

void UROS2SetSimStateSrv::GetRequest(FROSSetSimStateReq& Request) const
{
    Request.SetFromROS2(SetSimState_req);
}

void UROS2SetSimStateSrv::SetResponse(const FROSSetSimStateRes& Response)
{
    Response.SetROS2(SetSimState_res);
}

void UROS2SetSimStateSrv::GetResponse(FROSSetSimStateRes& Response) const
{
    Response.SetFromROS2(SetSimState_res);
}

void* UROS2SetSimStateSrv::GetRequest()
{
    return &SetSimState_req;
}

void* UROS2SetSimStateSrv::GetResponse()
{
    return &SetSimState_res;
}

FString UROS2SetSimStateSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}

FString UROS2SetSimStateSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}