// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/srv/ParamFile.srv - do not modify

#include "Srvs/ROS2ParamFile.h"





const rosidl_service_type_support_t* UROS2ParamFileSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(rosflight_msgs, srv, ParamFile);
}

void UROS2ParamFileSrv::Init()
{
    rosflight_msgs__srv__ParamFile_Request__init(&ParamFile_req);
    rosflight_msgs__srv__ParamFile_Response__init(&ParamFile_res);
}

void UROS2ParamFileSrv::Fini()
{
    rosflight_msgs__srv__ParamFile_Request__fini(&ParamFile_req);
    rosflight_msgs__srv__ParamFile_Response__fini(&ParamFile_res);
}

void UROS2ParamFileSrv::SetRequest(const FROSParamFileReq& Request)
{
    Request.SetROS2(ParamFile_req);
}

void UROS2ParamFileSrv::GetRequest(FROSParamFileReq& Request) const
{
    Request.SetFromROS2(ParamFile_req);
}

void UROS2ParamFileSrv::SetResponse(const FROSParamFileRes& Response)
{
    Response.SetROS2(ParamFile_res);
}

void UROS2ParamFileSrv::GetResponse(FROSParamFileRes& Response) const
{
    Response.SetFromROS2(ParamFile_res);
}

void* UROS2ParamFileSrv::GetRequest()
{
    return &ParamFile_req;
}

void* UROS2ParamFileSrv::GetResponse()
{
    return &ParamFile_res;
}

FString UROS2ParamFileSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}

FString UROS2ParamFileSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}