// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/srv/ParamSet.srv - do not modify

#include "Srvs/ROS2ParamSet.h"





const rosidl_service_type_support_t* UROS2ParamSetSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(rosflight_msgs, srv, ParamSet);
}

void UROS2ParamSetSrv::Init()
{
    rosflight_msgs__srv__ParamSet_Request__init(&ParamSet_req);
    rosflight_msgs__srv__ParamSet_Response__init(&ParamSet_res);
}

void UROS2ParamSetSrv::Fini()
{
    rosflight_msgs__srv__ParamSet_Request__fini(&ParamSet_req);
    rosflight_msgs__srv__ParamSet_Response__fini(&ParamSet_res);
}

void UROS2ParamSetSrv::SetRequest(const FROSParamSetReq& Request)
{
    Request.SetROS2(ParamSet_req);
}

void UROS2ParamSetSrv::GetRequest(FROSParamSetReq& Request) const
{
    Request.SetFromROS2(ParamSet_req);
}

void UROS2ParamSetSrv::SetResponse(const FROSParamSetRes& Response)
{
    Response.SetROS2(ParamSet_res);
}

void UROS2ParamSetSrv::GetResponse(FROSParamSetRes& Response) const
{
    Response.SetFromROS2(ParamSet_res);
}

void* UROS2ParamSetSrv::GetRequest()
{
    return &ParamSet_req;
}

void* UROS2ParamSetSrv::GetResponse()
{
    return &ParamSet_res;
}

FString UROS2ParamSetSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}

FString UROS2ParamSetSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
    return FString();
}