// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/Command.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rosflight_msgs/msg/command.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"


// Generated
#include "ROS2Command.generated.h"

USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSCommand
{
	GENERATED_BODY()

public:
		static constexpr uint8 MODE_PASS_THROUGH = 0;
	static constexpr uint8 MODE_ROLLRATE_PITCHRATE_YAWRATE_THROTTLE = 1;
	static constexpr uint8 MODE_ROLL_PITCH_YAWRATE_THROTTLE = 2;
	static constexpr uint8 IGNORE_NONE = 0;
	static constexpr uint8 IGNORE_QX = 1;
	static constexpr uint8 IGNORE_QY = 2;
	static constexpr uint8 IGNORE_QZ = 4;
	static constexpr uint8 IGNORE_FX = 8;
	static constexpr uint8 IGNORE_FY = 16;
	static constexpr uint8 IGNORE_FZ = 32;


	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	uint8 Mode = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	uint8 Ignore = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Qx = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Qy = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Qz = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Fx = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Fy = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Fz = 0.f;

	

	FROSCommand()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__msg__Command& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		Mode = in_ros_data.mode;

		Ignore = in_ros_data.ignore;

		Qx = in_ros_data.qx;

		Qy = in_ros_data.qy;

		Qz = in_ros_data.qz;

		Fx = in_ros_data.fx;

		Fy = in_ros_data.fy;

		Fz = in_ros_data.fz;

		
	}

	void SetROS2(rosflight_msgs__msg__Command& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		out_ros_data.mode = Mode;

		out_ros_data.ignore = Ignore;

		out_ros_data.qx = Qx;

		out_ros_data.qy = Qy;

		out_ros_data.qz = Qz;

		out_ros_data.fx = Fx;

		out_ros_data.fy = Fy;

		out_ros_data.fz = Fz;

		
	}
};

UCLASS()
class UNREALROSFLIGHT_API UROS2CommandMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSCommand& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSCommand& Output) const;
	
	virtual void* Get() override;

	UFUNCTION(BlueprintCallable)
	static uint8 CONST_MODE_PASS_THROUGH()
	{
		return FROSCommand::MODE_PASS_THROUGH;
	}
	UFUNCTION(BlueprintCallable)
	static uint8 CONST_MODE_ROLLRATE_PITCHRATE_YAWRATE_THROTTLE()
	{
		return FROSCommand::MODE_ROLLRATE_PITCHRATE_YAWRATE_THROTTLE;
	}
	UFUNCTION(BlueprintCallable)
	static uint8 CONST_MODE_ROLL_PITCH_YAWRATE_THROTTLE()
	{
		return FROSCommand::MODE_ROLL_PITCH_YAWRATE_THROTTLE;
	}
	UFUNCTION(BlueprintCallable)
	static uint8 CONST_IGNORE_NONE()
	{
		return FROSCommand::IGNORE_NONE;
	}
	UFUNCTION(BlueprintCallable)
	static uint8 CONST_IGNORE_QX()
	{
		return FROSCommand::IGNORE_QX;
	}
	UFUNCTION(BlueprintCallable)
	static uint8 CONST_IGNORE_QY()
	{
		return FROSCommand::IGNORE_QY;
	}
	UFUNCTION(BlueprintCallable)
	static uint8 CONST_IGNORE_QZ()
	{
		return FROSCommand::IGNORE_QZ;
	}
	UFUNCTION(BlueprintCallable)
	static uint8 CONST_IGNORE_FX()
	{
		return FROSCommand::IGNORE_FX;
	}
	UFUNCTION(BlueprintCallable)
	static uint8 CONST_IGNORE_FY()
	{
		return FROSCommand::IGNORE_FY;
	}
	UFUNCTION(BlueprintCallable)
	static uint8 CONST_IGNORE_FZ()
	{
		return FROSCommand::IGNORE_FZ;
	}
	


private:
	virtual FString MsgToString() const override;

	rosflight_msgs__msg__Command command_msg;
};