// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/SimState.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rosflight_msgs/msg/sim_state.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"
#include "Msgs/ROS2Pose.h"
#include "Msgs/ROS2Twist.h"
#include "Msgs/ROS2Acc.h"


// Generated
#include "ROS2SimState.generated.h"

USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSSimState
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSPose Pose;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSTwist Twist;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSAcc Acceleration;

	

	FROSSimState()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__msg__SimState& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		Pose.SetFromROS2(in_ros_data.pose);

		Twist.SetFromROS2(in_ros_data.twist);

		Acceleration.SetFromROS2(in_ros_data.acceleration);

		
	}

	void SetROS2(rosflight_msgs__msg__SimState& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		Pose.SetROS2(out_ros_data.pose);

		Twist.SetROS2(out_ros_data.twist);

		Acceleration.SetROS2(out_ros_data.acceleration);

		
	}
};

UCLASS()
class UNREALROSFLIGHT_API UROS2SimStateMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSSimState& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSSimState& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	rosflight_msgs__msg__SimState sim_state_msg;
};