// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/RCRaw.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rosflight_msgs/msg/rc_raw.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"


// Generated
#include "ROS2RCRaw.generated.h"

USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSRCRaw
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere)
	TArray<uint16> Values;

	

	FROSRCRaw()
	{
		Values.SetNumZeroed(8);

		
	}

	void SetFromROS2(const rosflight_msgs__msg__RCRaw& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		UROS2Utils::SequenceROSToUEArray<uint16, uint16>(in_ros_data.values, Values, 8);

		
	}

	void SetROS2(rosflight_msgs__msg__RCRaw& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		UROS2Utils::ArrayUEToROSSequence<uint16, uint16>(Values, out_ros_data.values, 8);

		
	}
};

UCLASS()
class UNREALROSFLIGHT_API UROS2RCRawMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSRCRaw& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSRCRaw& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	rosflight_msgs__msg__RCRaw rc_raw_msg;
};