// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/Attitude.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rosflight_msgs/msg/attitude.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"


// Generated
#include "ROS2Attitude.generated.h"

USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSAttitude
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FQuat Attitude = FQuat::Identity;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector AngularVelocity = FVector::ZeroVector;

	

	FROSAttitude()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__msg__Attitude& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		Attitude = UROS2Utils::QuatROSToUE(in_ros_data.attitude);

		AngularVelocity = UROS2Utils::VectorROSToUE<geometry_msgs__msg__Vector3>(in_ros_data.angular_velocity);

		
	}

	void SetROS2(rosflight_msgs__msg__Attitude& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		out_ros_data.attitude = UROS2Utils::QuatUEToROS(Attitude);

		out_ros_data.angular_velocity = UROS2Utils::VectorUEToROS<geometry_msgs__msg__Vector3>(AngularVelocity);

		
	}
};

UCLASS()
class UNREALROSFLIGHT_API UROS2AttitudeMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSAttitude& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSAttitude& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	rosflight_msgs__msg__Attitude attitude_msg;
};