// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/Error.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rosflight_msgs/msg/error.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"


// Generated
#include "ROS2Err.generated.h"

USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSErr
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString ErrorMessage;

	UPROPERTY(EditAnywhere)
	unsigned int ErrorCode = 0;

	UPROPERTY(EditAnywhere)
	unsigned int ResetCount = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bRearm = false;

	UPROPERTY(EditAnywhere)
	unsigned int Pc = 0;

	

	FROSErr()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__msg__Error& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		ErrorMessage = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.error_message);

		ErrorCode = in_ros_data.error_code;

		ResetCount = in_ros_data.reset_count;

		bRearm = in_ros_data.rearm;

		Pc = in_ros_data.pc;

		
	}

	void SetROS2(rosflight_msgs__msg__Error& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		UROS2Utils::StringUEToROS(ErrorMessage, out_ros_data.error_message);

		out_ros_data.error_code = ErrorCode;

		out_ros_data.reset_count = ResetCount;

		out_ros_data.rearm = bRearm;

		out_ros_data.pc = Pc;

		
	}
};

UCLASS()
class UNREALROSFLIGHT_API UROS2ErrMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSErr& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSErr& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	rosflight_msgs__msg__Error error_msg;
};