// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/OutputRaw.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rosflight_msgs/msg/output_raw.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"
#include "rosidl_runtime_c/primitives_sequence_functions.h"


// Generated
#include "ROS2OutputRaw.generated.h"

USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSOutputRaw
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TArray<float> Values;

	

	FROSOutputRaw()
	{
		Values.SetNumZeroed(14);

		
	}

	void SetFromROS2(const rosflight_msgs__msg__OutputRaw& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		UROS2Utils::SequenceROSToUEArray<float, float>(in_ros_data.values, Values, 14);

		
	}

	void SetROS2(rosflight_msgs__msg__OutputRaw& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		UROS2Utils::ArrayUEToROSSequence<float, float>(Values, out_ros_data.values, 14);

		
	}
};

UCLASS()
class UNREALROSFLIGHT_API UROS2OutputRawMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSOutputRaw& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSOutputRaw& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	rosflight_msgs__msg__OutputRaw output_raw_msg;
};