// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/Barometer.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rosflight_msgs/msg/barometer.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"


// Generated
#include "ROS2Barometer.generated.h"

USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSBarometer
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Altitude = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Pressure = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Temperature = 0.f;

	

	FROSBarometer()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__msg__Barometer& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		Altitude = in_ros_data.altitude;

		Pressure = in_ros_data.pressure;

		Temperature = in_ros_data.temperature;

		
	}

	void SetROS2(rosflight_msgs__msg__Barometer& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		out_ros_data.altitude = Altitude;

		out_ros_data.pressure = Pressure;

		out_ros_data.temperature = Temperature;

		
	}
};

UCLASS()
class UNREALROSFLIGHT_API UROS2BarometerMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSBarometer& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSBarometer& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	rosflight_msgs__msg__Barometer barometer_msg;
};