// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/Airspeed.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rosflight_msgs/msg/airspeed.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"


// Generated
#include "ROS2Airspeed.generated.h"

USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSAirspeed
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Velocity = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float DifferentialPressure = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Temperature = 0.f;

	

	FROSAirspeed()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__msg__Airspeed& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		Velocity = in_ros_data.velocity;

		DifferentialPressure = in_ros_data.differential_pressure;

		Temperature = in_ros_data.temperature;

		
	}

	void SetROS2(rosflight_msgs__msg__Airspeed& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		out_ros_data.velocity = Velocity;

		out_ros_data.differential_pressure = DifferentialPressure;

		out_ros_data.temperature = Temperature;

		
	}
};

UCLASS()
class UNREALROSFLIGHT_API UROS2AirspeedMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSAirspeed& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSAirspeed& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	rosflight_msgs__msg__Airspeed airspeed_msg;
};