// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/Status.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rosflight_msgs/msg/status.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"


// Generated
#include "ROS2Status.generated.h"

USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSStatus
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bArmed = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bFailsafe = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bRcOverride = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bOffboard = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	uint8 ControlMode = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	uint8 ErrorCode = 0;

	UPROPERTY(EditAnywhere)
	int16 NumErrors = 0;

	UPROPERTY(EditAnywhere)
	int16 LoopTimeUs = 0;

	

	FROSStatus()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__msg__Status& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		bArmed = in_ros_data.armed;

		bFailsafe = in_ros_data.failsafe;

		bRcOverride = in_ros_data.rc_override;

		bOffboard = in_ros_data.offboard;

		ControlMode = in_ros_data.control_mode;

		ErrorCode = in_ros_data.error_code;

		NumErrors = in_ros_data.num_errors;

		LoopTimeUs = in_ros_data.loop_time_us;

		
	}

	void SetROS2(rosflight_msgs__msg__Status& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		out_ros_data.armed = bArmed;

		out_ros_data.failsafe = bFailsafe;

		out_ros_data.rc_override = bRcOverride;

		out_ros_data.offboard = bOffboard;

		out_ros_data.control_mode = ControlMode;

		out_ros_data.error_code = ErrorCode;

		out_ros_data.num_errors = NumErrors;

		out_ros_data.loop_time_us = LoopTimeUs;

		
	}
};

UCLASS()
class UNREALROSFLIGHT_API UROS2StatusMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSStatus& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSStatus& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	rosflight_msgs__msg__Status status_msg;
};