// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/BatteryStatus.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rosflight_msgs/msg/battery_status.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Header.h"


// Generated
#include "ROS2BatteryStatus.generated.h"

USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSBatteryStatus
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSHeader Header;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Voltage = 0.f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float Current = 0.f;

	

	FROSBatteryStatus()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__msg__BatteryStatus& in_ros_data)
	{
    	Header.SetFromROS2(in_ros_data.header);

		Voltage = in_ros_data.voltage;

		Current = in_ros_data.current;

		
	}

	void SetROS2(rosflight_msgs__msg__BatteryStatus& out_ros_data) const
	{
    	Header.SetROS2(out_ros_data.header);

		out_ros_data.voltage = Voltage;

		out_ros_data.current = Current;

		
	}
};

UCLASS()
class UNREALROSFLIGHT_API UROS2BatteryStatusMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSBatteryStatus& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSBatteryStatus& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	rosflight_msgs__msg__BatteryStatus battery_status_msg;
};