// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/Airspeed.msg - do not modify

#include "Msgs/ROS2Airspeed.h"

#include "Kismet/GameplayStatics.h"



void UROS2AirspeedMsg::Init()
{
	rosflight_msgs__msg__Airspeed__init(&airspeed_msg);
}

void UROS2AirspeedMsg::Fini()
{
	rosflight_msgs__msg__Airspeed__fini(&airspeed_msg);
}

const rosidl_message_type_support_t* UROS2AirspeedMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rosflight_msgs, msg, Airspeed);
}

void UROS2AirspeedMsg::SetMsg(const FROSAirspeed& Inputs)
{
    Inputs.SetROS2(airspeed_msg);
}

void UROS2AirspeedMsg::GetMsg(FROSAirspeed& Outputs) const
{
    Outputs.SetFromROS2(airspeed_msg);
}

void* UROS2AirspeedMsg::Get()
{
	return &airspeed_msg;
}

FString UROS2AirspeedMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}