// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/RCRaw.msg - do not modify

#include "Msgs/ROS2RCRaw.h"

#include "Kismet/GameplayStatics.h"



void UROS2RCRawMsg::Init()
{
	rosflight_msgs__msg__RCRaw__init(&rc_raw_msg);
}

void UROS2RCRawMsg::Fini()
{
	rosflight_msgs__msg__RCRaw__fini(&rc_raw_msg);
}

const rosidl_message_type_support_t* UROS2RCRawMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rosflight_msgs, msg, RCRaw);
}

void UROS2RCRawMsg::SetMsg(const FROSRCRaw& Inputs)
{
    Inputs.SetROS2(rc_raw_msg);
}

void UROS2RCRawMsg::GetMsg(FROSRCRaw& Outputs) const
{
    Outputs.SetFromROS2(rc_raw_msg);
}

void* UROS2RCRawMsg::Get()
{
	return &rc_raw_msg;
}

FString UROS2RCRawMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}