// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/Status.msg - do not modify

#include "Msgs/ROS2Status.h"

#include "Kismet/GameplayStatics.h"



void UROS2StatusMsg::Init()
{
	rosflight_msgs__msg__Status__init(&status_msg);
}

void UROS2StatusMsg::Fini()
{
	rosflight_msgs__msg__Status__fini(&status_msg);
}

const rosidl_message_type_support_t* UROS2StatusMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rosflight_msgs, msg, Status);
}

void UROS2StatusMsg::SetMsg(const FROSStatus& Inputs)
{
    Inputs.SetROS2(status_msg);
}

void UROS2StatusMsg::GetMsg(FROSStatus& Outputs) const
{
    Outputs.SetFromROS2(status_msg);
}

void* UROS2StatusMsg::Get()
{
	return &status_msg;
}

FString UROS2StatusMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}