// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/SimState.msg - do not modify

#include "Msgs/ROS2SimState.h"

#include "Kismet/GameplayStatics.h"



void UROS2SimStateMsg::Init()
{
	rosflight_msgs__msg__SimState__init(&sim_state_msg);
}

void UROS2SimStateMsg::Fini()
{
	rosflight_msgs__msg__SimState__fini(&sim_state_msg);
}

const rosidl_message_type_support_t* UROS2SimStateMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rosflight_msgs, msg, SimState);
}

void UROS2SimStateMsg::SetMsg(const FROSSimState& Inputs)
{
    Inputs.SetROS2(sim_state_msg);
}

void UROS2SimStateMsg::GetMsg(FROSSimState& Outputs) const
{
    Outputs.SetFromROS2(sim_state_msg);
}

void* UROS2SimStateMsg::Get()
{
	return &sim_state_msg;
}

FString UROS2SimStateMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}