// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/Attitude.msg - do not modify

#include "Msgs/ROS2Attitude.h"

#include "Kismet/GameplayStatics.h"



void UROS2AttitudeMsg::Init()
{
	rosflight_msgs__msg__Attitude__init(&attitude_msg);
}

void UROS2AttitudeMsg::Fini()
{
	rosflight_msgs__msg__Attitude__fini(&attitude_msg);
}

const rosidl_message_type_support_t* UROS2AttitudeMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rosflight_msgs, msg, Attitude);
}

void UROS2AttitudeMsg::SetMsg(const FROSAttitude& Inputs)
{
    Inputs.SetROS2(attitude_msg);
}

void UROS2AttitudeMsg::GetMsg(FROSAttitude& Outputs) const
{
    Outputs.SetFromROS2(attitude_msg);
}

void* UROS2AttitudeMsg::Get()
{
	return &attitude_msg;
}

FString UROS2AttitudeMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}