// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/PwmOutput.msg - do not modify

#include "Msgs/ROS2PwmOutput.h"

#include "Kismet/GameplayStatics.h"



void UROS2PwmOutputMsg::Init()
{
	rosflight_msgs__msg__PwmOutput__init(&pwm_output_msg);
}

void UROS2PwmOutputMsg::Fini()
{
	rosflight_msgs__msg__PwmOutput__fini(&pwm_output_msg);
}

const rosidl_message_type_support_t* UROS2PwmOutputMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rosflight_msgs, msg, PwmOutput);
}

void UROS2PwmOutputMsg::SetMsg(const FROSPwmOutput& Inputs)
{
    Inputs.SetROS2(pwm_output_msg);
}

void UROS2PwmOutputMsg::GetMsg(FROSPwmOutput& Outputs) const
{
    Outputs.SetFromROS2(pwm_output_msg);
}

void* UROS2PwmOutputMsg::Get()
{
	return &pwm_output_msg;
}

FString UROS2PwmOutputMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}