// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/BatteryStatus.msg - do not modify

#include "Msgs/ROS2BatteryStatus.h"

#include "Kismet/GameplayStatics.h"



void UROS2BatteryStatusMsg::Init()
{
	rosflight_msgs__msg__BatteryStatus__init(&battery_status_msg);
}

void UROS2BatteryStatusMsg::Fini()
{
	rosflight_msgs__msg__BatteryStatus__fini(&battery_status_msg);
}

const rosidl_message_type_support_t* UROS2BatteryStatusMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rosflight_msgs, msg, BatteryStatus);
}

void UROS2BatteryStatusMsg::SetMsg(const FROSBatteryStatus& Inputs)
{
    Inputs.SetROS2(battery_status_msg);
}

void UROS2BatteryStatusMsg::GetMsg(FROSBatteryStatus& Outputs) const
{
    Outputs.SetFromROS2(battery_status_msg);
}

void* UROS2BatteryStatusMsg::Get()
{
	return &battery_status_msg;
}

FString UROS2BatteryStatusMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}