// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/GNSS.msg - do not modify

#include "Msgs/ROS2GNSS.h"

#include "Kismet/GameplayStatics.h"



void UROS2GNSSMsg::Init()
{
	rosflight_msgs__msg__GNSS__init(&gnss_msg);
}

void UROS2GNSSMsg::Fini()
{
	rosflight_msgs__msg__GNSS__fini(&gnss_msg);
}

const rosidl_message_type_support_t* UROS2GNSSMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rosflight_msgs, msg, GNSS);
}

void UROS2GNSSMsg::SetMsg(const FROSGNSS& Inputs)
{
    Inputs.SetROS2(gnss_msg);
}

void UROS2GNSSMsg::GetMsg(FROSGNSS& Outputs) const
{
    Outputs.SetFromROS2(gnss_msg);
}

void* UROS2GNSSMsg::Get()
{
	return &gnss_msg;
}

FString UROS2GNSSMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}