// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/Barometer.msg - do not modify

#include "Msgs/ROS2Barometer.h"

#include "Kismet/GameplayStatics.h"



void UROS2BarometerMsg::Init()
{
	rosflight_msgs__msg__Barometer__init(&barometer_msg);
}

void UROS2BarometerMsg::Fini()
{
	rosflight_msgs__msg__Barometer__fini(&barometer_msg);
}

const rosidl_message_type_support_t* UROS2BarometerMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rosflight_msgs, msg, Barometer);
}

void UROS2BarometerMsg::SetMsg(const FROSBarometer& Inputs)
{
    Inputs.SetROS2(barometer_msg);
}

void UROS2BarometerMsg::GetMsg(FROSBarometer& Outputs) const
{
    Outputs.SetFromROS2(barometer_msg);
}

void* UROS2BarometerMsg::Get()
{
	return &barometer_msg;
}

FString UROS2BarometerMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}