// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/Command.msg - do not modify

#include "Msgs/ROS2Command.h"

#include "Kismet/GameplayStatics.h"



void UROS2CommandMsg::Init()
{
	rosflight_msgs__msg__Command__init(&command_msg);
}

void UROS2CommandMsg::Fini()
{
	rosflight_msgs__msg__Command__fini(&command_msg);
}

const rosidl_message_type_support_t* UROS2CommandMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rosflight_msgs, msg, Command);
}

void UROS2CommandMsg::SetMsg(const FROSCommand& Inputs)
{
    Inputs.SetROS2(command_msg);
}

void UROS2CommandMsg::GetMsg(FROSCommand& Outputs) const
{
    Outputs.SetFromROS2(command_msg);
}

void* UROS2CommandMsg::Get()
{
	return &command_msg;
}

FString UROS2CommandMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}