// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/Error.msg - do not modify

#include "Msgs/ROS2Err.h"

#include "Kismet/GameplayStatics.h"



void UROS2ErrMsg::Init()
{
	rosflight_msgs__msg__Error__init(&error_msg);
}

void UROS2ErrMsg::Fini()
{
	rosflight_msgs__msg__Error__fini(&error_msg);
}

const rosidl_message_type_support_t* UROS2ErrMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rosflight_msgs, msg, Error);
}

void UROS2ErrMsg::SetMsg(const FROSErr& Inputs)
{
    Inputs.SetROS2(error_msg);
}

void UROS2ErrMsg::GetMsg(FROSErr& Outputs) const
{
    Outputs.SetFromROS2(error_msg);
}

void* UROS2ErrMsg::Get()
{
	return &error_msg;
}

FString UROS2ErrMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}