// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/msg/OutputRaw.msg - do not modify

#include "Msgs/ROS2OutputRaw.h"

#include "Kismet/GameplayStatics.h"



void UROS2OutputRawMsg::Init()
{
	rosflight_msgs__msg__OutputRaw__init(&output_raw_msg);
}

void UROS2OutputRawMsg::Fini()
{
	rosflight_msgs__msg__OutputRaw__fini(&output_raw_msg);
}

const rosidl_message_type_support_t* UROS2OutputRawMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(rosflight_msgs, msg, OutputRaw);
}

void UROS2OutputRawMsg::SetMsg(const FROSOutputRaw& Inputs)
{
    Inputs.SetROS2(output_raw_msg);
}

void UROS2OutputRawMsg::GetMsg(FROSOutputRaw& Outputs) const
{
    Outputs.SetFromROS2(output_raw_msg);
}

void* UROS2OutputRawMsg::Get()
{
	return &output_raw_msg;
}

FString UROS2OutputRawMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}