// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/srv/ParamGet.srv - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rosflight_msgs/srv/param_get.h"

// rclUE
#include "Srvs/ROS2GenericSrv.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)



// Generated
#include "ROS2ParamGet.generated.h"

// potential problem: if this struct is defined multiple times!
USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSParamGetReq
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString Name;

	

	FROSParamGetReq()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__srv__ParamGet_Request& in_ros_data)
	{
    	Name = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.name);

		
	}

	void SetROS2(rosflight_msgs__srv__ParamGet_Request& out_ros_data) const
	{
    	UROS2Utils::StringUEToROS(Name, out_ros_data.name);

		
	}
};

USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSParamGetRes
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bExists = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	double Value = 0.f;

	

	FROSParamGetRes()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__srv__ParamGet_Response& in_ros_data)
	{
    	bExists = in_ros_data.exists;

		Value = in_ros_data.value;

		
	}

	void SetROS2(rosflight_msgs__srv__ParamGet_Response& out_ros_data) const
	{
    	out_ros_data.exists = bExists;

		out_ros_data.value = Value;

		
	}
};

UCLASS()
class UNREALROSFLIGHT_API UROS2ParamGetSrv : public UROS2GenericSrv
{
	GENERATED_BODY()

public:
  	UFUNCTION(BlueprintCallable)
	virtual void Init() override;

  	UFUNCTION(BlueprintCallable)
	virtual void Fini() override;

	virtual const rosidl_service_type_support_t* GetTypeSupport() const override;
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void SetRequest(const FROSParamGetReq& Request);
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void GetRequest(FROSParamGetReq& Request) const;
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void SetResponse(const FROSParamGetRes& Response);
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void GetResponse(FROSParamGetRes& Response) const;
	
	virtual void* GetRequest() override;
	virtual void* GetResponse() override;

	
	

private:
	virtual FString SrvRequestToString() const override;
	virtual FString SrvResponseToString() const override;

	rosflight_msgs__srv__ParamGet_Request ParamGet_req;
	rosflight_msgs__srv__ParamGet_Response ParamGet_res;
};