// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/srv/SetSimState.srv - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rosflight_msgs/srv/set_sim_state.h"

// rclUE
#include "Srvs/ROS2GenericSrv.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2SimState.h"



// Generated
#include "ROS2SetSimState.generated.h"

// potential problem: if this struct is defined multiple times!
USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSSetSimStateReq
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSSimState State;

	

	FROSSetSimStateReq()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__srv__SetSimState_Request& in_ros_data)
	{
    	State.SetFromROS2(in_ros_data.state);

		
	}

	void SetROS2(rosflight_msgs__srv__SetSimState_Request& out_ros_data) const
	{
    	State.SetROS2(out_ros_data.state);

		
	}
};

USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSSetSimStateRes
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bSuccess = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString Message;

	

	FROSSetSimStateRes()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__srv__SetSimState_Response& in_ros_data)
	{
    	bSuccess = in_ros_data.success;

		Message = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.message);

		
	}

	void SetROS2(rosflight_msgs__srv__SetSimState_Response& out_ros_data) const
	{
    	out_ros_data.success = bSuccess;

		UROS2Utils::StringUEToROS(Message, out_ros_data.message);

		
	}
};

UCLASS()
class UNREALROSFLIGHT_API UROS2SetSimStateSrv : public UROS2GenericSrv
{
	GENERATED_BODY()

public:
  	UFUNCTION(BlueprintCallable)
	virtual void Init() override;

  	UFUNCTION(BlueprintCallable)
	virtual void Fini() override;

	virtual const rosidl_service_type_support_t* GetTypeSupport() const override;
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void SetRequest(const FROSSetSimStateReq& Request);
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void GetRequest(FROSSetSimStateReq& Request) const;
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void SetResponse(const FROSSetSimStateRes& Response);
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void GetResponse(FROSSetSimStateRes& Response) const;
	
	virtual void* GetRequest() override;
	virtual void* GetResponse() override;

	
	

private:
	virtual FString SrvRequestToString() const override;
	virtual FString SrvResponseToString() const override;

	rosflight_msgs__srv__SetSimState_Request SetSimState_req;
	rosflight_msgs__srv__SetSimState_Response SetSimState_res;
};