// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from rosflight_msgs/srv/ParamFile.srv - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "rosflight_msgs/srv/param_file.h"

// rclUE
#include "Srvs/ROS2GenericSrv.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)



// Generated
#include "ROS2ParamFile.generated.h"

// potential problem: if this struct is defined multiple times!
USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSParamFileReq
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString Filename;

	

	FROSParamFileReq()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__srv__ParamFile_Request& in_ros_data)
	{
    	Filename = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.filename);

		
	}

	void SetROS2(rosflight_msgs__srv__ParamFile_Request& out_ros_data) const
	{
    	UROS2Utils::StringUEToROS(Filename, out_ros_data.filename);

		
	}
};

USTRUCT(Blueprintable)
struct UNREALROSFLIGHT_API FROSParamFileRes
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	bool bSuccess = false;

	

	FROSParamFileRes()
	{
		
	}

	void SetFromROS2(const rosflight_msgs__srv__ParamFile_Response& in_ros_data)
	{
    	bSuccess = in_ros_data.success;

		
	}

	void SetROS2(rosflight_msgs__srv__ParamFile_Response& out_ros_data) const
	{
    	out_ros_data.success = bSuccess;

		
	}
};

UCLASS()
class UNREALROSFLIGHT_API UROS2ParamFileSrv : public UROS2GenericSrv
{
	GENERATED_BODY()

public:
  	UFUNCTION(BlueprintCallable)
	virtual void Init() override;

  	UFUNCTION(BlueprintCallable)
	virtual void Fini() override;

	virtual const rosidl_service_type_support_t* GetTypeSupport() const override;
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void SetRequest(const FROSParamFileReq& Request);
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void GetRequest(FROSParamFileReq& Request) const;
	
	// used by service
  	UFUNCTION(BlueprintCallable)
	void SetResponse(const FROSParamFileRes& Response);
	
	// used by client
  	UFUNCTION(BlueprintCallable)
	void GetResponse(FROSParamFileRes& Response) const;
	
	virtual void* GetRequest() override;
	virtual void* GetResponse() override;

	
	

private:
	virtual FString SrvRequestToString() const override;
	virtual FString SrvResponseToString() const override;

	rosflight_msgs__srv__ParamFile_Request ParamFile_req;
	rosflight_msgs__srv__ParamFile_Response ParamFile_res;
};